-- Add reactions table for emoji reactions to messages
-- Users can react to messages with emojis

create table public.reactions (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.messages(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  emoji text not null,
  created_at timestamptz default now(),
  -- One reaction per user per message per emoji
  unique(message_id, user_id, emoji)
);

-- Index for performance
create index on public.reactions (message_id);
create index on public.reactions (user_id);

-- RLS policies for reactions
alter table public.reactions enable row level security;

-- Anyone in the class can view reactions
create policy "reactions_select_policy" on public.reactions
  for select
  using (
    exists (
      select 1 from public.messages m
      join public.class_members cm on m.class_id = cm.class_id
      where m.id = reactions.message_id
      and cm.user_id = auth.uid()
    )
  );

-- Users can add reactions to messages in their classes
create policy "reactions_insert_policy" on public.reactions
  for insert
  with check (
    auth.uid() = user_id
    and exists (
      select 1 from public.messages m
      join public.class_members cm on m.class_id = cm.class_id
      where m.id = message_id
      and cm.user_id = auth.uid()
    )
  );

-- Users can delete their own reactions
create policy "reactions_delete_policy" on public.reactions
  for delete
  using (auth.uid() = user_id);

-- Enable realtime for reactions
alter publication supabase_realtime add table public.reactions;

-- Add comment
comment on table public.reactions is 'Emoji reactions to messages';
