-- KlasseChatten Database Schema
-- Run this in Supabase SQL Editor or via Supabase CLI

-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- =============================================
-- USERS & PROFILES
-- =============================================
-- Profiles table (extends Supabase auth.users)
create table public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text check (role in ('child','guardian','adult')) not null,
  display_name text not null,
  created_at timestamptz default now()
);

-- =============================================
-- SCHOOLS & CLASSES
-- =============================================
create table public.schools (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  municipality text
);

create table public.classes (
  id uuid primary key default gen_random_uuid(),
  school_id uuid references public.schools(id),
  label text not null,           -- fx "3.A"
  grade_level int not null,      -- 0..9
  invite_code text unique not null, -- 8-10 tegn
  settings jsonb default '{}'::jsonb,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table public.class_members (
  class_id uuid references public.classes(id) on delete cascade,
  user_id uuid references auth.users(id) on delete cascade,
  role_in_class text check (role_in_class in ('child','guardian','adult')) not null,
  status text default 'active',
  joined_at timestamptz default now(),
  primary key (class_id, user_id)
);

-- =============================================
-- ROOMS & MESSAGES
-- =============================================
create table public.rooms (
  id uuid primary key default gen_random_uuid(),
  class_id uuid references public.classes(id) on delete cascade,
  name text not null,            -- "general"
  type text check (type in ('general','topic')) default 'general',
  is_locked boolean default false,
  created_by uuid references auth.users(id),
  created_at timestamptz default now()
);

create table public.messages (
  id bigint generated by default as identity primary key,
  room_id uuid references public.rooms(id) on delete cascade,
  class_id uuid not null,        -- denormaliseret for policy performance
  user_id uuid references auth.users(id),
  body text not null,
  reply_to bigint references public.messages(id),
  created_at timestamptz default now(),
  edited_at timestamptz,
  deleted_at timestamptz,
  meta jsonb default '{}'::jsonb
);

-- Index for performance
create index on public.messages (class_id, room_id, created_at);

-- =============================================
-- MODERATION & REPORTS
-- =============================================
create table public.reports (
  id uuid primary key default gen_random_uuid(),
  reporter_user_id uuid references auth.users(id),
  subject_type text check (subject_type in ('message','user')) not null,
  subject_id text not null,
  class_id uuid not null,
  reason text,
  status text default 'open',
  created_at timestamptz default now()
);

create table public.moderation_events (
  id uuid primary key default gen_random_uuid(),
  subject_type text not null,
  subject_id text not null,
  class_id uuid not null,
  rule text,
  score numeric,
  labels text[],
  status text check (status in ('flagged','hidden','cleared')) not null,
  reviewer_user_id uuid,
  created_at timestamptz default now()
);

-- =============================================
-- GUARDIAN RELATIONSHIPS
-- =============================================
create table public.guardian_links (
  child_user_id uuid references auth.users(id) on delete cascade,
  guardian_user_id uuid references auth.users(id) on delete cascade,
  relationship text,
  consent_status text default 'granted',
  consent_at timestamptz default now(),
  primary key (child_user_id, guardian_user_id)
);

-- =============================================
-- PUSH NOTIFICATIONS
-- =============================================
create table public.push_tokens (
  user_id uuid references auth.users(id) on delete cascade,
  platform text check (platform in ('ios','android','web')),
  token text,
  created_at timestamptz default now(),
  primary key (user_id, token)
);

-- =============================================
-- TRIGGERS
-- =============================================
-- Denormaliser class_id på messages via trigger
create or replace function public.set_message_class_id()
returns trigger language plpgsql as $$
begin
  select r.class_id into new.class_id from public.rooms r where r.id = new.room_id;
  return new;
end $$;

create trigger trg_messages_class
before insert on public.messages
for each row execute function public.set_message_class_id();

-- =============================================
-- ROW LEVEL SECURITY (RLS)
-- =============================================
-- Enable RLS on all tables
alter table public.profiles enable row level security;
alter table public.schools enable row level security;
alter table public.classes enable row level security;
alter table public.class_members enable row level security;
alter table public.rooms enable row level security;
alter table public.messages enable row level security;
alter table public.reports enable row level security;
alter table public.moderation_events enable row level security;
alter table public.guardian_links enable row level security;
alter table public.push_tokens enable row level security;

-- =============================================
-- BASIC RLS POLICIES (customize as needed)
-- =============================================

-- Profiles: Users can read their own profile
create policy "Users can view own profile"
  on public.profiles for select
  using (auth.uid() = user_id);

create policy "Users can update own profile"
  on public.profiles for update
  using (auth.uid() = user_id);

-- Class members can view other members in their classes
create policy "Class members can view profiles in their classes"
  on public.profiles for select
  using (
    exists (
      select 1 from public.class_members cm1
      join public.class_members cm2 on cm1.class_id = cm2.class_id
      where cm1.user_id = auth.uid()
      and cm2.user_id = profiles.user_id
    )
  );

-- Classes: Members can view their classes
create policy "Users can view classes they are members of"
  on public.classes for select
  using (
    exists (
      select 1 from public.class_members
      where class_id = classes.id
      and user_id = auth.uid()
    )
  );

-- Class members: Users can view members in their classes
create policy "Users can view class members in their classes"
  on public.class_members for select
  using (
    exists (
      select 1 from public.class_members cm
      where cm.class_id = class_members.class_id
      and cm.user_id = auth.uid()
    )
  );

-- Rooms: Class members can view rooms in their classes
create policy "Class members can view rooms"
  on public.rooms for select
  using (
    exists (
      select 1 from public.class_members
      where class_id = rooms.class_id
      and user_id = auth.uid()
    )
  );

-- Messages: Class members can view messages in their classes
create policy "Class members can view messages"
  on public.messages for select
  using (
    exists (
      select 1 from public.class_members
      where class_id = messages.class_id
      and user_id = auth.uid()
    )
    and deleted_at is null
  );

-- Messages: Class members can insert messages
create policy "Class members can create messages"
  on public.messages for insert
  with check (
    exists (
      select 1 from public.class_members
      where class_id = messages.class_id
      and user_id = auth.uid()
    )
    and user_id = auth.uid()
  );

-- Messages: Users can update their own messages
create policy "Users can update own messages"
  on public.messages for update
  using (user_id = auth.uid());

-- Guardian links: Users can view their guardian relationships
create policy "Users can view own guardian links"
  on public.guardian_links for select
  using (
    auth.uid() = child_user_id
    or auth.uid() = guardian_user_id
  );

-- Push tokens: Users can manage their own tokens
create policy "Users can manage own push tokens"
  on public.push_tokens for all
  using (auth.uid() = user_id);

-- Reports: Authenticated users can create reports
create policy "Authenticated users can create reports"
  on public.reports for insert
  with check (auth.uid() = reporter_user_id);

-- Moderation events: Only viewable by adults/moderators
create policy "Adults can view moderation events"
  on public.moderation_events for select
  using (
    exists (
      select 1 from public.class_members cm
      join public.profiles p on p.user_id = cm.user_id
      where cm.class_id = moderation_events.class_id
      and cm.user_id = auth.uid()
      and p.role = 'adult'
    )
  );
